Models/ErrorViewModel.cs
namespace Mvc101.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Mvc101.Models;

namespace Mvc101.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    // Action methods - represents home page
    // has its own view
    public IActionResult Index()
    {
        string[] days = { "Mon", "Tues", "Wed", "Thurs", "Fri", "Sat", "Sun" };
        ViewData["days"] = days;
        return View();
    }
    // represents privacy page 
    // http://localhost:5094/Home/Privacy 
    // Home represents controller Privacy represents action method
    // has its own view
    public IActionResult Privacy()
    {
        return View();
    }
    // creating my own action method for a view
    public IActionResult Bogus()
    {
        // Dictionary entry with key author value james bond
        ViewData["author"] = "James Bond";
        //gave it name Date that displays date.
        ViewBag.Date = DateTime.Now;
        ViewData["Date"] = DateTime.Now;
        string[] days = { "Mon", "Tues", "Wed", "Thurs", "Fri", "Sat", "Sun" };

        return View(days);
    }

    //error catcher
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

Controllers/ProcessController.cs
using System.Reflection;
using System;
using System.Diagnostics;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace Mvc101.Controllers
{
    public class ProcessController : Controller
    {
        // GET: Process
        // public ActionResult Index()
        // {
        //     //can pass as viewbag, viewData and as a concrete class
        //     Process[] procs = Process.GetProcesses();
        //     ViewBag.Procs = procs;
        //     return View(procs);
        // }
        public ActionResult Index()
        {
            return View(Process.GetProcesses());
        }
        public ActionResult Display(int id)
        {
            return View(Process.GetProcessById(id));
        }

    }
}

Views/Home/Bogus.cshtml
@model string[]
@{
    ViewData["Title"] = "Bogus Page";
    //gets the just date
    var date = (System.DateTime)ViewBag.Date;
    // same thind diff syntax
    var date2 = (System.DateTime) ViewData["Date"]!;
}

<h1>@ViewData["Title"]</h1>
@* <p>This is the first ASP.NET page authored by @ViewData["author"] on @ViewBag.Date!</p> *@
@* gets just date no time *@
<p>This is the first ASP.NET page authored by @ViewData["author"] on @date.ToShortDateString()!</p>

@* passing in concrete class *@
<ul>
    @foreach (var item in Model)
    {
        <li>@item</li>
    }
</ul>

Views/Home/Index.cshtml
@{
    //c# island can put any c# code
    //dont put data in your views
    ViewData["Title"] = "Home Page";
    string[]? days = ViewData["days"] as string[];
}

<div class="text-center">
    <h1 class="display-4" style="color: tomato">Welcome to COMP 4870!</h1>
    <ul>
        @foreach (var item in days!)
        {
            <li>@item</li>
        }
    </ul>
</div>

Views/Process/Display.cshtml
@model System.Diagnostics.Process

@{
    ViewData["Title"] = "Process Details";
}

<div>
    <table>
        <tr>
            <td>ID</td>
            <td>@Model.Id</td>
        </tr>
        <tr>
            <td>Name</td>
            <td>@Model.ProcessName</td>
        </tr>
        <tr>
            <td>Count</td>
            <td>@Model.HandleCount</td>
        </tr>
    </table>
</div>

Views/Process/Index.cshtml
@* @using System.Diagnostics *@
@model System.Diagnostics.Process[]
@{
    ViewData["Title"] = "Process Page";
    @* var procs = ViewBag.Procs as Process[]; *@
}

@* <div>
    <h2>
        @ViewData["Title"]
    </h2>
    <ul>
        @foreach(var item in procs) {
            <li>
                if(item.ProcessName.Trim().Length > 0){
                    @item.ProcessName;
                }
            </li>
        }
    </ul>
</div> *@

<div>
    <h2>
        @ViewData["Title"]
    </h2>
    <ul>
        @foreach(var item in Model) {
            <li><a asp-controller="Process"
                asp-action="Display"
                asp-route-id="@item.Id">@item.ProcessName</a>
            </li>
        }
    </ul>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Mvc101</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Mvc101.styles.css" asp-append-version="true" />
</head>
 @* views are injected into this template *@
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Mvc101</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Bogus">Bogus</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Process" asp-action="Index">Processes</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    @* This section is the injection point for your views *@
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Mvc101 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)


</body>
</html>